name: Format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - stable
    - "v*"

jobs:
  clang-tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    container: silkeh/clang:14
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Prepare env
      run: >
        apt-get update && apt-get install -y python3-dev python3-pip python3-setuptools python3-wheel
        --no-install-recommends

    - name: Upgrade pybind11
      run: python3 -m pip install --upgrade pybind11 --prefer-binary

    - name: Run clang-tidy
      run: python3 setup.py clang_tidy --warning-as-errors
