name: Format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - stable
    - "v*"

jobs:
  pre-commit:
    name: Format and static analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get history and tags for SCM versioning to work
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        # Slow hooks are marked with manual - slow is okay here, run them too
        extra_args: --hook-stage manual --all-files

  clang-tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    container: silkeh/clang:10
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v2

    - name: Prepare env
      run: >
        apt-get update && apt-get install -y python3-dev python3-pip python3-setuptools python3-wheel
        --no-install-recommends

    - name: Upgrade pybind11
      run: python3 -m pip install --upgrade pybind11 --prefer-binary

    - name: Run Clang-Tidy
      run: python3 setup.py clang_tidy --warning-as-errors
